version: '3.7'

volumes:
  certs:
  grafana_data:
  prometheus_data:

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--api.insecure=true" # Enable the Traefik dashboard on port 8080
      - "--providers.docker=true" # Enable Docker as a provider
      - "--entrypoints.web.address=:80" # Define entrypoint for HTTP
      - "--entrypoints.websecure.address=:443" # Define entrypoint for HTTPS
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      # Set up LetsEncrypt
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=samprada3@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Set up the TLS configuration for our websecure listener
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=pariswomencinefest.world
      - --entrypoints.websecure.http.tls.domains[0].sans=*.pariswomencinefest.world
      - --entrypoints.websecure.http.tls.domains[1].main=ottawafilm.site
      - --entrypoints.websecure.http.tls.domains[1].sans=*.ottawafilm.site
      - --entrypoints.websecure.http.tls.domains[2].main=indianashort.com.
      - --entrypoints.websecure.http.tls.domains[2].sans=*.indianashort.com

      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addrouterslabels=true
      - --metrics.prometheus.addServicesLabels=true
    environment:
      - TZ=Asia/Tehran
      - "CLOUDFLARE_EMAIL=samprada3@gmail.com"
      - "CLOUDFLARE_API_KEY=a18bae34d559bb88a6ccd2b9eb527cfef83d6"
      - "CLOUDFLARE_DNS_API_TOKEN=umo7u4rwHEdB4Ej-V9Y8q3cNQieQNOuP5ZHJwfGLV"
      - "CLOUDFLARE_ZONE_API_TOKEN=Z656Qi90j1pvAD4ETdMI912Wl3ZImTBKy0xcPPIU"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - certs:/letsencrypt
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.rule=Host(`traefik.pariswomencinefest.world`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"

#  whoami:
#    image: docker.io/traefik/whoami:v1.10.1
#    labels:
#    - traefik.http.routers.whoami.rule=Host(`whoami.pariswomencinefest.world`)
#    - traefik.http.services.whoami.loadbalancer.server.port=80
#    - traefik.http.routers.whoami.entrypoints=websecure
#    - traefik.http.routers.whoami.tls.certresolver=letsencrypt

#  prometheus:
#    container_name: prometheus
#    image: docker.io/prom/prometheus:v2.48.1
#    volumes:
#    - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
#    - prometheus_data:/prometheus
#    labels:
#      - traefik.enable=true
#      - traefik.http.services.prometheus.loadbalancer.server.port=9090
#      - traefik.http.routers.prometheus.rule=Host(`prometheus.pariswomencinefest.world`)
#      - traefik.http.middlewares.prometheus.basicauth.users=root:{SHA}3Hbp8MAAbo+RngxRXGbbujmC94U= # root:root
#      - traefik.http.routers.prometheus.middlewares=prometheus
#    restart: always

#  grafana:
#    container_name: grafana
#    image: docker.io/grafana/grafana
#    environment:
#    - GF_SECURITY_ADMIN_USER=admin
#    - GF_SECURITY_ADMIN_PASSWORD=Sin@2022
#    volumes:
#    - grafana_data:/var/lib/grafana
#    labels:
#      - traefik.enable=true
#      - traefik.http.services.grafana.loadbalancer.server.port=3000
#      - traefik.http.routers.grafana.rule=Host(`dash.pariswomencinefest.world`)
#    restart: always

  pariswomencinefest:
    image: nginx:alpine
    container_name: pariswomencinefest
    volumes:
      - ./site-content/pariswomencinefest/web:/usr/share/nginx/html
      - ./site-content/pariswomencinefest/nginx:/etc/nginx/conf.d
    labels:
      - "traefik.http.routers.pariswomencinefest.rule=Host(`pariswomencinefest.world`)"
      - "traefik.http.routers.pariswomencinefest.entrypoints=websecure"
      - "traefik.http.services.pariswomencinefest.loadbalancer.server.port=80"
      - traefik.http.routers.pariswomencinefest.tls.certresolver=letsencrypt

  indianashort:
    image: nginx:alpine
    container_name: indianashort
    volumes:
      - ./site-content/indianashort/web:/usr/share/nginx/html
      - ./site-content/indianashort/nginx:/etc/nginx/conf.d
      - ./site-content/indianashort/movies:/var/www/html/videos
      - ./site-content/indianashort/certs/s1:/var/www/html/certs
    labels:
      - "traefik.http.routers.indianashort.rule=Host(`indianashort.com`)"
      - "traefik.http.routers.indianashort.entrypoints=websecure"
      - "traefik.http.services.indianashort.loadbalancer.server.port=80"
      - traefik.http.routers.indianashort.tls.certresolver=letsencrypt

  screening:
    image: nginx:alpine
    container_name: screening
    volumes:
      - ./site-content/screening/web:/usr/share/nginx/html
      - ./site-content/screening/nginx:/etc/nginx/conf.d
      - ./site-content/screening/movies:/var/www/html/videos
    labels:
      - "traefik.http.routers.screening.rule=Host(`screening.indianashort.com`)"
      - "traefik.http.routers.screening.entrypoints=websecure"
      - "traefik.http.services.screening.loadbalancer.server.port=80"
      - "traefik.http.routers.screening.tls.certresolver=letsencrypt"

  ottawa:
    image: nginx:alpine
    container_name: ottawa
    volumes:
      - ./site-content/ottawafilm/web:/usr/share/nginx/html
      - ./site-content/ottawafilm/nginx:/etc/nginx/conf.d
      - ./site-content/ottawafilm/certs/s1:/var/www/html/certs
    labels:
      - "traefik.http.routers.ottawa.rule=Host(`ottawafilm.site`)"
      - "traefik.http.routers.ottawa.entrypoints=websecure"
      - "traefik.http.services.ottawa.loadbalancer.server.port=80"
      - "traefik.http.routers.ottawa.tls.certresolver=letsencrypt"
